# This is a basic workflow to help you get started with Actions

name: Codespell

# Controls when the workflow will run
on:
  schedule:
    # Trigger Codespell at a scheduled time
    # * is a special character in YAML so you have to quote this string
    - cron: '30 0 * * *'
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Codespell"
  Codespell:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check spelling errors
        uses: codespell-project/actions-codespell@master
        with:
          check_filenames: false
          skip: ./.git,./SandboxiePlus/MiscHelpers/*,./Sandboxie/msgs/Text-*-*.txt,./SandboxiePlus/SandMan/*.ts,./Installer/Languages.iss
          builtin: clear,rare,code
          ignore_words_list: pevent,doubleclick,parm,parms,etcp,ois,ba,ptd,modell,namesd,stdio,uint,errorstring
