# This is a basic workflow to help you get started with Actions

name: Spell check

# Controls when the workflow will run
on:
  schedule:
    # Trigger Codespell at a scheduled time
    # * is a special character in YAML so you have to quote this string
    - cron: '30 0 * * *'
  # Triggers the workflow on push or pull request events
 # push:
  #  branches:
  #  - 'master'
  pull_request:
    branches:
  #  - 'master'
    - '*typo*'
    - '*spell*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Codespell"
  Codespell:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check spelling errors
        uses: codespell-project/actions-codespell@master
        with:
          check_filenames: false
          skip: "./.git,./Sandboxie/msgs/Text-*-*.txt,./Sandboxie/msgs/report/Report-*.txt,./SandboxiePlus/SandMan/*.ts,./Installer/Languages.iss,./Installer/isl/*.isl,./Sandboxie/common/Detours/Makefile"
          builtin: clear,rare,code
          # only lowercase letters are allowed here
          ignore_words_list: "wil,unknwn,tolen,pevent,doubleclick,parm,parms,etcp,ois,ba,ptd,modell,namesd,stdio,uint,errorstring,ontext,atend,deque,ecounter,nmake,namess,inh,daa,varient"
